services:
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    volumes:
      - weather-redis-data:/var/lib/redis
  web:
    build: .
    ports:
      - '3000:3000'
volumes:
  weather-redis-data:
